# Generated by Django 5.2.14 on 2026-05-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_number', models.IntegerField()),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('is_eligible', models.BooleanField(default=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizen',
                'verbose_name_plural': 'Citizens',
                'db_table': 'citizens',
                'ordering': ['-created_at'],
            },
        ),
    ]
