# Generated by Django 5.2.14 on 2026-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
