# Generated by Django 6.0.5 on 2026-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
