# Generated by Django 6.0.5 on 2026-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_vote_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='vote',
            name='unique_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
