# Generated by Django 5.2.14 on 2026-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_position_candidate_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='symbols/'),
        ),
    ]
