# Generated by Django 5.2.14 on 2026-05-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('vote_cast', 'Vote Cast'), ('election_created', 'Election Created'), ('election_updated', 'Election Updated'), ('election_deleted', 'Election Deleted'), ('candidate_added', 'Candidate Added'), ('candidate_updated', 'Candidate Updated'), ('candidate_deleted', 'Candidate Deleted'), ('user_registration_failed', 'User Registration Failed'), ('user_registered', 'User Registered'), ('user_verified', 'User Verified')], max_length=50),
        ),
    ]
