# Generated by Django 6.0.5 on 2026-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('vote_cast', 'Vote Cast'), ('vote_verified', 'Vote Verified'), ('election_created', 'Election Created'), ('election_updated', 'Election Updated'), ('election_deleted', 'Election Deleted'), ('election_activated', 'Election Activated'), ('election_closed', 'Election Closed'), ('candidate_added', 'Candidate Added'), ('candidate_updated', 'Candidate Updated'), ('candidate_deleted', 'Candidate Deleted'), ('user_registered', 'User Registered'), ('user_verified', 'User Verified'), ('citizenship_verification', 'Citizenship Verification'), ('citizenship_verification_failed', 'Citizenship Verification Failed'), ('resend_verification', 'Resend Verification'), ('profile_updated', 'Profile Updated'), ('admin_login', 'Admin Login'), ('audit_log_viewed', 'Audit Log Viewed')], max_length=50),
        ),
    ]
